-- Import phpMyAdmin : références sectorielles uniquement
USE cayribe;

DELETE FROM sector_references;
DELETE FROM sector_categories;

INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('agriculture', 'Agriculture', 'green', 0);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('numerique', 'Numérique', 'red', 1);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('sante-medico-social', 'Santé & Médico-social', 'orange', 2);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('transport', 'Transport', 'blue', 3);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('energie', 'Energie', 'blue', 4);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('environnement', 'Environnement', 'green', 5);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('industrie', 'Industrie', 'orange', 6);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('btp', 'BTP', 'purple', 7);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('tourisme', 'Tourisme', 'green', 8);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('public', 'Public', 'red', 9);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('agrotransformation', 'Agrotransformation', 'purple', 10);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('economie-circulaire', 'Economie circulaire', 'blue', 11);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('culture-loisirs', 'Culture & Loisirs', 'green', 12);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('services-entreprises', 'Services aux entreprises', 'purple', 13);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('commerce-distribution', 'Commerce & distribution', 'orange', 14);
INSERT INTO sector_categories (id, label, color, sort_order) VALUES ('artisanat', 'Artisanat', 'red', 15);

INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agriculture', 'Entreprise de production et transformation agricole spécialisée en cultures rares', 'étude de faisabilité cultures alternées, business plan, diversification des activités agricoles, identité de marque', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agriculture', 'Coopérative agricole (filière porcine)', 'étude de faisabilité technico-économique, stratégie opérationnelle, recherche de financements, stratégie de diversification, stratégie de communication', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agriculture', 'Production de plantes aromatiques et médicinales', 'stratégie marketing et structuration commerciale, plan de communication', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agriculture', 'Ferme aquaponique', 'analyse de marché, modélisation économique, financement LEADER', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('numerique', 'Entreprise spécialisée dans la domotique', 'définition de la stratégie marketing, structuration commerciale, stratégie de communication, mise en place d’outils de gestion opérationnelle', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('numerique', 'Entreprise spécialisée dans l’achat groupé sur internet', 'élaboration du business plan export, recherche de financements, valorisation financière', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('numerique', 'Application de gestion de services à la personne', 'modélisation économique, stratégie de développement', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('numerique', 'Application de gestion d''invendus alimentaires', 'stratégie commerciale', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('sante-medico-social', 'Projet hospitalier innovant', 'gestion du projet, de ses partenaires, recherche de financement, stratégie de valorisation, externalisation au sein d’un véhicule juridique adapté', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('sante-medico-social', 'Plateforme médicale innovante', 'montage du dossier et financement FEDER', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('sante-medico-social', 'Etablissement médico-social', 'structuration du projet associatif, stratégie de développement', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('sante-medico-social', 'Projet de coworking d''auxiliaires médicaux', 'étude de faisabilité, modèle économique, stratégie de financement, financement LEADER', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('transport', 'Start-up de construction et d’exploitation d’un cargo voile', 'Construction d’un business model, analyse de coût de revient et de rentabilité, campagne de prospection commerciale à l’export, recherche de financements', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('transport', 'Projet innovant de solution d''autopartage', 'analyse de marché, construction du business plan', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('transport', 'Ligue professionnelle de voile', 'Etude stratégique de la filière Voile', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('transport', 'Projet de transporteur routier', 'construction du modèle économique, réalisation du business plan', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('energie', 'Start-up de production d’électricité par procédé innovant (brevet)', 'revue de business plan, stratégie financière, du diligences préalables à la recherche d''investisseurs', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('energie', 'Centre d''excellence sur la géothermie', 'analyse prospective, construction du modèle économique, étude de faisabilité, étude de préfiguration, montage du projet et financement INTERREG', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('energie', 'Start-up de production de biogaz et de GNV', 'étude de la filière, analyse de la chaîne de valeur, médiation projet partenariat public - privé', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('energie', 'Start-up de fabrication de borne de recharge solaire connectée', 'stratégie marketing, analyse coûts de revient, modélisation économique , recherche de financements, financement ARI', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('environnement', 'Entreprise de valorisation de déchets d’élagage en charbon', 'étude de faisabilité technique, définition d’un modèle économique, analyse de marché, construction d’un business plan', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('environnement', 'Entreprise de traitement de déchets', 'étude de faisabilité et de valorisation du broyat de verre', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('environnement', 'Association de protection de l''environnement', 'audit organisationnel, recommandations, montage financement CCT', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('environnement', 'Entreprise de traitement de déchets dangereux', 'étude d''opportunité export Trinidad & Tobago', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('industrie', 'Entreprise de construction de mobilier parasismique', 'structuration technique, structuration commerciale, pré-industrialisation, étude de protection intellectuelle, recherche de financements', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('industrie', 'Distillerie (rhum)', 'étude des coûts de revient, audit industriel, recommandations', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('industrie', 'Fabrication industrielle d''escaliers sur mesure et de menuiseries en bois', 'audit industriel, recommandations', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('industrie', 'Enteprise industrielle de fabrication de jus de canne', 'stratégie export, étude de coûts de revient, audit industriel, recommandations', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('btp', 'Entreprise de détection de réseaux enterrés', 'Etude de marché, audit organisationnel, conception d’un outil opérationnel de pilotage de l’activité, Accompagnement à la certification de l’entreprise', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('btp', 'Entreprise spécialisée dans l’étanchéité, la réhabilitation et la protection d’ouvrages en génie civil', 'étude de faisabilité, élaboration de business plan, recherche de financements', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('btp', 'Plateau technique dans le domaine de l''énergie et de la construction des bâtiments', 'étude de faisabilité, modèle économique, préfiguration', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('btp', 'Projet de renovation d''un bâtiment en centre-ville', 'etude fonctionnelle, étude économique, assistance au pilotage du projet, stratégie de financement', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('tourisme', 'Fédération professionnelle', 'structuration de filière', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('tourisme', 'Entreprise specialisé dans le tourisme industriel', 'étude de marché, modèle économique, stratégie de financement, chéque innovation', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('tourisme', 'Projet de reprise d''un complexe hôtelier en Guyane', 'due dilligences préalables (diagnostic financier et réglementaire)', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('tourisme', 'Agence de voyage réceptive', 'audit organisationnel, marketing / communication, réglementaire, financier; recommandations stratégiques', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('public', NULL, 'Gestion de dispositifs d''accompagnement d''entreprises collectifs et individuels', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('public', NULL, 'Réalisation d''annuaire de structures d''accompagnement et de financement', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('public', NULL, 'Etudes emploi / formations Guadeloupe et Martinique', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('public', NULL, 'Etudes de marchés, d''opportunités et de faisabilité de pépinière d''entreprise et d''espaces de coworking', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agrotransformation', 'Entreprise semi-industrielle de transformation du manioc', 'modèle économique, stratégie de développement, projet de R&D, recherche de financement, financement LEADER, ARI', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agrotransformation', 'Entreprise semi-industrielle innovante de transformation de produits laitiers', 'analyse de marché, étude économique, stratégie de financement', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agrotransformation', 'Entreprise industrielle innovante de fabrication d''alimentation infantile', 'modélisation économique, stratégie marketing et commerciale', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('agrotransformation', 'Entreprise semi-industrielle de transformation de noix de cajou', 'stratégie de développement à l''international, détermination des coûts de revient', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('economie-circulaire', 'Entreprise innovante de valorisation de déchets végétaux et d''excréments d''animaux', 'analyse de marché, étude économique, stratégie de financement', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('economie-circulaire', 'Entreprise innovante de valorisation de dechets de bananiers', 'étude de marché, modèle économique, stratégie de financement, chèque innovation, financement ARI', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('economie-circulaire', 'Entreprise de valorisation de dechets de noix de coco', 'analyse de marché, modélisation économique, calcul de coûts de revient, stratégie de financement', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('economie-circulaire', 'Projet de valorisation de dressing haut de gamme', 'modélisation économique, stratégie marketing et commerciale', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('culture-loisirs', 'Entreprise d''édition de bande dessinée pour enfants', 'modèle économique, stratégie de développement', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('culture-loisirs', 'Projet de bibliobus', 'analyse de marché, construction d''un modèle économique', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('culture-loisirs', 'Entreprise d''excursions en bateau', 'recherche de sources de financements, portage juridique, analyse de coûts de revient, préfinancement subvention', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('culture-loisirs', 'Projet de base nautique / café solidaire', 'stratégie de financement, construction d''un budget prévisionnel, recommandations organisationnelles, financement LEADER', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('services-entreprises', 'Projet innovant de station de lavage', 'modèle économique, étude de faisabilité, financement LEADER', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('services-entreprises', 'Entreprise de gestion d''espace de coworking', 'modèle économique, stratégie marketing et commerciale', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('services-entreprises', 'Entreprise de sécurité privée', 'assistance à réponse à plusieurs appels d''offres, structuration d''un mémoire technique, formation', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('services-entreprises', 'Entreprise d''entretien et de réparation de poids lourds', 'analyse de marché, optimisation de modèle économique, stratégie financière', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('commerce-distribution', 'Entreprise de distribution d''équipements photovoltaïques', 'Audit organisationnel, recommandations, stratégie de développement', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('commerce-distribution', 'Entreprise de distribution de matériaux et d''articles de bricolage', 'etude de faisabilité de projet d''extension et de diversification', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('commerce-distribution', 'Entreprise de commercialisation de distributeurs alimentaires', 'étude économique, étude de faisabilité, stratégie de financement', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('commerce-distribution', 'Entreprise de distribution de papeterie, produits éducatifs, culturels et de loisirs', 'analyse stratégique, analyse marketing, audit organisationnel, analyse de coûts de revient, optimisation process', 3);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('artisanat', 'Entreprise artisanale de fabrication de produits haut de gamme', 'analyse de marché, analyse de process, détermination des coûts de revient, stratégie de développement international', 0);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('artisanat', 'Entreprise artisanale de production de boudin et assimilés', 'Analyse du marché, analyse de process, modélisation économique', 1);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('artisanat', 'Entreprise artisanale de création de bijoux, calebasses, tableaux et coffrets garnis', 'analyse de marché, modelisation économique, financement LEADER', 2);
INSERT INTO sector_references (sector_id, highlight, text, sort_order) VALUES ('artisanat', 'Entreprise artisanale de fabrication de produits cosmétiques', 'portage juridique, analyse de process, modélisation économique, financement LEADER', 3);
